id: opecha:P005533
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2855
  title: གཤིན་རྗེ་གཤེད་སྐོར་གྱི་བླ་མ་བརྒྱུད་པའི་ཆོས་འབྱུང་གདུལ་བྱའི་རེ་འདོད་སྐོང་བ་ཡིད་བཞིན་ནོར་བུའི་འཕྲེང་བ
  volume: ''
  author: ''
